# These are the versions of our backend to be supported
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# install dependencies, for python3.4 setuptools needs to be upgraded first
install:
  - "pip install -U setuptools"
  - "pip install -r requirements.txt"
  - "pip install coveralls"

# we use mongodb as our database
services:
  - mongodb

before_install:
  - openssl aes-256-cbc -K $encrypted_fedd13c2de32_key -iv $encrypted_fedd13c2de32_iv -in google_secrets.json.enc -out google_secrets.json -d

# Seed the mongodb with some test data
before_script:
  - bash mock_data/db_init.sh

# Run the test suite
script:
  - coverage run -m nose tests

after_success:
  - coveralls

# notify if there is a change in build status
notification:
  email:
    on_success: change
    on_failure: change

# monitor only these branches
branches:
  only:
    - master
    - dev