language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
install: "pip install -r requirements.txt"

services:
  - mongodb

before_script:
  - bash mock_data/db_init.sh
  - cd coder_directory_api

script:
  - nosetests

notification:
  email:
    on_success: change
    on_failure: change

branches:
  only:
    - master
    - dev