version: "3"
services:
  coder:
    build: .
    ports:
      - "6000:3000"
    environment:
      - HOST=0.0.0.0
      - API_ENV=PROD
      - API_SECRET=/app/coder_directory_api/prod_settings.json
      - GOOGLE=/app/google_secrets.json
    volumes:
      - ./coder_directory_api/prod_settings.json:/app/coder_directory_api/prod_settings.json
      - ./google_secrets.json:/app/google_secrets.json
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - /data:/data/db
    ports:
      - "2000:27017"
    command: mongod