version: "3"
services:
  coder:
    build: .
    ports:
      - "6000:3000"
    environment:
      - HOST=0.0.0.0
      - ENV=PROD
      - SECRET=dev_settings.json
    links:
      - mongodb
  mongodb:
    image: mongo
    volumes:
      - /data:/data/db